CREATE TABLE `users` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `full_name` VARCHAR(255) NOT NULL,
    `company_name` VARCHAR(255) DEFAULT NULL,
    `mobile` VARCHAR(20) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `state` VARCHAR(100) NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `address` TEXT NOT NULL,
    `pincode` VARCHAR(20) NOT NULL,
    `category` ENUM(
        'agent_broker',
        'builder_developer',
        'architect',
        'interior_decorator',
        'building_contractor',
        'vaastu_consultant',
        'home_inspection',
        'property_consultant'
    ) NOT NULL,
    `sub_category` VARCHAR(100) DEFAULT NULL,
    `profile_photo` VARCHAR(500) DEFAULT NULL,
    `logo` VARCHAR(500) DEFAULT NULL,
    `experience` VARCHAR(100) DEFAULT NULL,
    `about_business` TEXT DEFAULT NULL,
    `service_areas` JSON DEFAULT NULL,
    `website` VARCHAR(255) DEFAULT NULL,
    `whatsapp_number` VARCHAR(20) DEFAULT NULL,
    `extra_fields` JSON DEFAULT NULL,
    `mobile_verified` TINYINT(1) NOT NULL DEFAULT 0,
    `email_verified` TINYINT(1) NOT NULL DEFAULT 0,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_email` (`email`),
    UNIQUE KEY `uk_mobile` (`mobile`),
    INDEX `idx_category` (`category`),
    INDEX `idx_status` (`status`),
    INDEX `idx_city` (`city`),
    INDEX `idx_state` (`state`),
    INDEX `idx_full_name` (`full_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
